//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class bitacora
    {
        public int id_bitacora { get; set; }
        public System.DateTime fecha { get; set; }
        public string accion { get; set; }
        public Nullable<int> id_usuario { get; set; }
        public Nullable<int> id_prosprecto { get; set; }
        public Nullable<int> id_reporte { get; set; }
        public Nullable<int> id_evento { get; set; }
        public Nullable<int> id_permiso { get; set; }
        public Nullable<int> id_producto { get; set; }
        public Nullable<int> id_rol { get; set; }
        public Nullable<int> id_seguimiento { get; set; }
        public Nullable<int> id_sesion { get; set; }
        public Nullable<int> id_tipo_producto { get; set; }
        public Nullable<int> id_venta { get; set; }
    
        public virtual evento evento { get; set; }
        public virtual permiso permiso { get; set; }
        public virtual reporte reporte { get; set; }
        public virtual seguimiento seguimiento { get; set; }
        public virtual sesion sesion { get; set; }
        public virtual usuario usuario { get; set; }
        public virtual venta venta { get; set; }
        public virtual prospecto prospecto { get; set; }
        public virtual producto producto { get; set; }
        public virtual tipo_producto tipo_producto { get; set; }
    }
}
