//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evaluacione
    {
        public evaluacione()
        {
            this.preguntas = new HashSet<pregunta>();
        }
    
        public int id_evaluacion { get; set; }
        public int usuario_evaluado { get; set; }
        public int porcentaje_desactivacion { get; set; }
        public int curso_evaluado { get; set; }
    
        public virtual ICollection<pregunta> preguntas { get; set; }
    }
}
