//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using Newtonsoft.Json;
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public evento()
        {
            this.bitacoras = new HashSet<bitacora>();
            this.prospectos = new HashSet<prospecto>();
        }

        [JsonProperty(PropertyName = "idevento")]
        public int id_evento { get; set; }
        [JsonProperty(PropertyName = "lugar")]
        public string lugar { get; set; }
        [JsonProperty(PropertyName = "fechaInicio")]
        public System.DateTime fecha_inicio { get; set; }
        [JsonProperty(PropertyName = "fechaFin")]
        public System.DateTime fecha_fin { get; set; }

        [JsonProperty(PropertyName = "bitacoras")]
        public virtual ICollection<bitacora> bitacoras { get; set; }

        [JsonProperty(PropertyName = "prospectos")]
        public virtual ICollection<prospecto> prospectos { get; set; }
    }
}
