//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class evento
    {
        public evento()
        {
            this.prospectos = new HashSet<prospecto>();
            this.bitacoras = new HashSet<bitacora>();
        }
    
        public int id_evento { get; set; }
        public string lugar { get; set; }
        public System.DateTime fecha_inicio { get; set; }
        public System.DateTime fecha_fin { get; set; }
    
        public virtual ICollection<prospecto> prospectos { get; set; }
        public virtual ICollection<bitacora> bitacoras { get; set; }
    }
}
