//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class kpi
    {
        public int id_kpi { get; set; }
        public int id_tipo { get; set; }
        public string descripcion { get; set; }
    
        public virtual tipo_kpi tipo_kpi { get; set; }
    }
}
