//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class permiso
    {
        public permiso()
        {
            this.bitacoras = new HashSet<bitacora>();
            this.rols = new HashSet<rol>();
        }
    
        public int id_permiso { get; set; }
        public string nombre { get; set; }
        public string descripcion { get; set; }
    
        public virtual ICollection<bitacora> bitacoras { get; set; }
        public virtual ICollection<rol> rols { get; set; }
    }
}
