//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class prospecto
    {
        public prospecto()
        {
            this.bitacoras = new HashSet<bitacora>();
            this.tipo_producto = new HashSet<tipo_producto>();
            this.usuarios = new HashSet<usuario>();
        }
    
        public int id_prospecto { get; set; }
        public string nombre { get; set; }
        public string apellidos { get; set; }
        public System.DateTime fecha_nacimiento { get; set; }
        public string procedencia { get; set; }
        public bool estado { get; set; }
        public string telefono { get; set; }
        public string email { get; set; }
        public string direccion { get; set; }
        public bool interesado { get; set; }
        public bool cliente { get; set; }
        public Nullable<int> id_evento { get; set; }
    
        public virtual ICollection<bitacora> bitacoras { get; set; }
        public virtual evento evento { get; set; }
        public virtual ICollection<tipo_producto> tipo_producto { get; set; }
        public virtual ICollection<usuario> usuarios { get; set; }
    }
}
