//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta
    {
        public respuesta()
        {
            this.preguntas = new HashSet<pregunta>();
        }
    
        public int id_respuesta { get; set; }
        public string respuesta1 { get; set; }
        public int puntaje { get; set; }
    
        public virtual ICollection<pregunta> preguntas { get; set; }
    }
}
