//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class respuesta
    {
        public respuesta()
        {
            this.preguntas = new HashSet<pregunta>();
        }
    
        public int id_respuesta { get; set; }
        public string respuesta1 { get; set; }
        public Nullable<int> puntaje { get; set; }
    
        public virtual ICollection<pregunta> preguntas { get; set; }
    }
}
