//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class rol
    {
        public rol()
        {
            this.usuarios = new HashSet<usuario>();
            this.permisos = new HashSet<permiso>();
        }
    
        public int id_rol { get; set; }
        public string nombre { get; set; }
        public bool activo { get; set; }
    
        public virtual ICollection<usuario> usuarios { get; set; }
        public virtual ICollection<permiso> permisos { get; set; }
    }
}
