//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class seguimiento
    {
        public seguimiento()
        {
            this.bitacoras = new HashSet<bitacora>();
        }
    
        public int id_seguimiento { get; set; }
        public int id_prospecto { get; set; }
        public System.DateTime fecha { get; set; }
        public string comentario { get; set; }
    
        public virtual ICollection<bitacora> bitacoras { get; set; }
    }
}
