//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_kpi
    {
        public tipo_kpi()
        {
            this.kpis = new HashSet<kpi>();
        }
    
        public int id_tipo { get; set; }
        public string nombre { get; set; }
    
        public virtual ICollection<kpi> kpis { get; set; }
    }
}
