//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI_Sistema_Cenfotec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class venta
    {
        public venta()
        {
            this.productos = new HashSet<producto>();
            this.bitacoras = new HashSet<bitacora>();
        }
    
        public int id_venta { get; set; }
        public int id_usuario { get; set; }
        public Nullable<decimal> monto { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string tipo { get; set; }
    
        public virtual usuario usuario { get; set; }
        public virtual ICollection<producto> productos { get; set; }
        public virtual ICollection<bitacora> bitacoras { get; set; }
    }
}
